INSERT INTO PRODUCT (DESCRIPTION, SIZE, COLOR, PRICE, STOCK, ACTIVE) VALUES ( 'Polo Manga Corta', 'M', 'VERDE', 29.90, 50, true);
INSERT INTO PRODUCT (DESCRIPTION, SIZE, COLOR, PRICE, STOCK, ACTIVE) VALUES ( 'Polo Manga Corta', 'S', 'ROJO', 29.90, 50, true);
INSERT INTO PRODUCT (DESCRIPTION, SIZE, COLOR, PRICE, STOCK, ACTIVE) VALUES ( 'Polo Manga Larga', 'M', 'AZUL', 29.90, 50, true);
INSERT INTO PRODUCT (DESCRIPTION, SIZE, COLOR, PRICE, STOCK, ACTIVE) VALUES ( 'Polo Manga Larga', 'S', 'NEGRO', 29.90, 0, false);
INSERT INTO PRODUCT (DESCRIPTION, SIZE, COLOR, PRICE, STOCK, ACTIVE) VALUES ( 'Polo Manga Corta', 'L', 'BLANCO', 35.50, 100, true);

INSERT INTO CUSTOMER (NAME, LAST_NAME, EMAIL, CELLPHONE, PASSWORD) VALUES ('Aimar', 'Berrocal', 'aimar@gmail.com','978143966', '123456');