INSERT INTO PRODUCT (DESCRIPTION, SIZE, COLOR, PRICE, STOCK, ACTIVE) VALUES ( 'Polo Manga Corta', 'M', 'VERDE', 35, 24, true);
INSERT INTO PRODUCT (DESCRIPTION, SIZE, COLOR, PRICE, STOCK, ACTIVE) VALUES ( 'Polo Manga Corta', 'S', 'ROJO', 35, 24, true);
INSERT INTO PRODUCT (DESCRIPTION, SIZE, COLOR, PRICE, STOCK, ACTIVE) VALUES ( 'Polo Manga Larga', 'M', 'AZUL', 35, 12, true);
INSERT INTO PRODUCT (DESCRIPTION, SIZE, COLOR, PRICE, STOCK, ACTIVE) VALUES ( 'Polo Manga Larga', 'S', 'NEGRO', 35, 0, false);
INSERT INTO PRODUCT (DESCRIPTION, SIZE, COLOR, PRICE, STOCK, ACTIVE) VALUES ( 'Polo Manga Corta', 'L', 'BLANCO', 35, 24, true);

INSERT INTO CUSTOMER (NAME, LAST_NAME, EMAIL, CELLPHONE, PASSWORD) VALUES ('Aimar', 'Berrocal', 'aimar@gmail.com','978143966', '123456');
INSERT INTO CUSTOMER (NAME, LAST_NAME, EMAIL, CELLPHONE, PASSWORD) VALUES ('Juan', 'Carlos', 'juan@gmail.com','97333921', '123456');